server:
  servlet:
    context-path: /api

blog:
  auth:
    token:
      sign-key: signKey012345678901234567890123456789
      valid-time: 3000000

web:
  cors:
    allowed-origins: "*"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"